name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: burrunan/gradle-cache-action@v1
        name: Gradle Build
        with:
          job-id: jdk8
          arguments: build
